argo-cd:
  dex:
    enabled: false

  redis-ha:
    enabled: true

  controller:
    enableStatefulSet: true
    args:
      statusProcessors: "50"
      operationProcessors: "25"

  server:
    autoscaling:
      enabled: true
      minReplicas: 2
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2