argo-cd:
  dex:
    enabled: false
  controller:
    enableStatefulSet: true
    args:
      statusProcessors: "50"
      operationProcessors: "25"
  server:
    extraArgs:
      - --insecure
    config:
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm