argo-cd:
  dex:
    enabled: true

  redis-ha:
    enabled: true

  controller:
    enableStatefulSet: true
    args:
      statusProcessors: "50"
      operationProcessors: "25"

  server:
    ingress:
      hosts:
        - k8s-argocd-argocdin-f7b3b69363-410852681.us-east-1.elb.amazonaws.com
    certificate:
      domain: k8s-argocd-argocdin-f7b3b69363-410852681.us-east-1.elb.amazonaws.com
    autoscaling:
      enabled: true
      minReplicas: 2
    extraArgs:
      - --insecure
    config:
      url: http://k8s-argocd-argocdin-f7b3b69363-410852681.us-east-1.elb.amazonaws.com
      repositories: |
        - type: helm
          name: argo-cd
          url: https://argoproj.github.io/argo-helm
      dex.config: |
        connectors:
          - type: saml
            id: okta
            name: Okta
            config:
              ssoURL: https://dev-15757292.okta.com/app/dev-15757292_argocd_1/exk4wwfirz9Cysj915d7/sso/saml
              caData: |
                LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxRENDQXBDZ0F3SUJBZ0lHQVlDT3lNQWVNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1JR1VNUXN3Q1FZRFZRUUdFd0pWVXpFVE1CRUcNCkExVUVDQXdLUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnd3TlUyRnVJRVp5WVc1amFYTmpiekVOTUFzR0ExVUVDZ3dFVDJ0MFlURVUNCk1CSUdBMVVFQ3d3TFUxTlBVSEp2ZG1sa1pYSXhGVEFUQmdOVkJBTU1ER1JsZGkweE5UYzFOekk1TWpFY01Cb0dDU3FHU0liM0RRRUoNCkFSWU5hVzVtYjBCdmEzUmhMbU52YlRBZUZ3MHlNakExTURReE1URTFNREphRncwek1qQTFNRFF4TVRFMk1ESmFNSUdVTVFzd0NRWUQNClZRUUdFd0pWVXpFVE1CRUdBMVVFQ0F3S1EyRnNhV1p2Y201cFlURVdNQlFHQTFVRUJ3d05VMkZ1SUVaeVlXNWphWE5qYnpFTk1Bc0cNCkExVUVDZ3dFVDJ0MFlURVVNQklHQTFVRUN3d0xVMU5QVUhKdmRtbGtaWEl4RlRBVEJnTlZCQU1NREdSbGRpMHhOVGMxTnpJNU1qRWMNCk1Cb0dDU3FHU0liM0RRRUpBUllOYVc1bWIwQnZhM1JoTG1OdmJUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQURnZ0VQQURDQ0FRb0MNCmdnRUJBTFl6SmxWcVljZXZyZExncE5rSFIvdDFQRm1tdDhIZ3ZxUjlud0hpUmVKVU5maGNlZXZSS0syYjMyem9UajcrVjUxZThMSloNCkdabEk2Z25rUzhtZEtSR0h5WmhxZXJaUmtBanUrdWVyL0NCdmlnQkYyYTBDY0lVQmx0Ti9OQkg2SEdibmlwUG90dUJ3eHpqbUo5SisNCjZ4M2l0ZmsxN1VDZ0ZpUHhUZFFBdXdPdW44Mk9wS1ppYS8ybElKQ293WElQVWN4ZHVucVBRVUFkODZtTlBReE9VTXZUOUozM3VRcXENCmlFZXRyVGowWjUvWmhZekpPODZsQUFDT3dWRXIwV3lqa1EwZjlOYVlkWFo0NTBpTllpeGFxQVRWaUl3ZC9oQ2dMdEdKc2RFS1lseU0NCnRBWlA2N1EwTXhQcWNhU1VLNDZZRHhWZ2JHNGJvd3VVZzFWWkJXczk2bE1DQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUENCktTUzkwZEFnQmp3NUhCVnRBS1ZjVHZBWjMyRll3K2ZsOUpQcXMvVm9wR1U4Sms3dnpXUmYrMnNBUFVSbGZ6cGFTL1dGNkU5d1JJaHMNCmJBL2RmdzRTaXplUDk1VmlXK1IvR0NPQ0x0bzNoVWNKUFYwQ0ViaXVmY3JraFUwVit6N1M1U3EwalhYbkI1R3hXWjZ1NXR6VzlpWGQNCjJLamFVTG1pekxhUElvend4WmJ5YlZLNDRRbnN2Tnh6blBldHFzWHFmZm95elB5NFpDV0xrcFBwVXZER3p5ME81bjBrbmx6dWhBRnMNCjdJM1IyblY2RFRQQkI2SGRUYWtGYVpsTUJxZUQweGlaRE5sWk82cjZqN0xzNFppM0djYWdPaDBjd0N3eFJzek91M0NCS3NjWGQwNUwNClp3V09jQ3IraWNQaGFJYnZqNXRVOTVXNEExd3JNRjE3VjhVYmR3PT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
              redirectURI: http://k8s-argocd-argocdin-f7b3b69363-410852681.us-east-1.elb.amazonaws.com/api/dex/callback
              usernameAttr: email
              emailAttr: email
              groupsAttr: group

  repoServer:
    autoscaling:
      enabled: true
      minReplicas: 2